services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB:   ${DB_NAME:-habits}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME:     ${DB_NAME:-habits}
      DB_USER:     ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST:     ${DB_HOST:-db}
      DB_PORT:     ${DB_PORT:-5432}

volumes:
  postgres_data: