# Generated by Django 5.0 on 2024-09-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habittracker_alter_habit_complete_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habittracker',
            old_name='habits',
            new_name='habit',
        ),
    ]
