# Generated by Django 5.0 on 2024-09-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_rename_habits_habittracker_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habittracker',
            old_name='complete',
            new_name='completed',
        ),
    ]
